name: flake8

on:
    - push
    - pull_request

jobs:
  lint:
    if: always()
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.11
          uses: actions/setup-python@v5
          with:
            python-version: 3.11

        - name: Install dependencies
          run: |  
            python -m pip install --upgrade pip
            python -m pip install tox
        
        - name: Run linting with tox
          env:
            TOXENV: "lint"
          run: tox
